### ISSUE TITLE
BBSR-2 Erstellung GML-Generator

### ISSUE THREAD

**Issue by pkorduan** [srahn/kvwmap#2]
- [x] Abfragen aller Leaf Elemente aus Schema xplan_model
- [x] Abfragen der Daten aus Schema gml_classes
- [x] Erzeugen von GML in eine Datei

**Comment by RKraetschmer** [comment]
Meiner Meinung nach sollte an der derzeitigen GML (Stand 09:42, 13.06.16) noch folgendes eingefügt/verändert werden:
- In der XML-Deklaration sollte encoding und standalone enthalten sein, d.h. es sollte wie folgt aussehen: `<?xml version="1.0" encoding="utf-8" standalone="yes"?>`
- Das derzeitige Modell ist derzeit unter http://xplan-raumordnung.de/devk/model/xplangml/raumordnungsmodell/  hinterlegt. Gegen dies muss die GML-Datei validieren. Sobald die Homepage mit diesem upgedatet wird, sollte devk aus den Namespaces entnommen werden
  D.h. `<XPlanAuszug>` sollte vorerst wie folgt aussehen:

```
<XPlanAuszug xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:wfs="http://www.opengis.net/wfs"
 xmlns:gml="http://www.opengis.net/gml"
 xmlns:xlink="http://www.w3.org/1999/xlink"
 xmlns:xplan="http://xplan-raumordnung.de/devk/model/xplangml/raumordnungsmodell"
 xmlns="http://xplan-raumordnung.de/devk/model/xplangml/raumordnungsmodell"
 xsi:schemaLocation="http://xplan-raumordnung.de/devk/model/xplangml/raumordnungsmodell/ ../../Schema/XPlanung-Operationen.xsd"
 >
```

(Der Namespace wfs: wird bisjetzt nicht verwendet und könnte entfernt werden, ist aber im Normalfall in einer XPlan-Datei mitenthalten, auch wenn diese ihn nicht verwendet.)
- gml:boundedBy positionen sollte für jeden Plan definiert oder festgehalten werden, z.B. über Informationen in  XP_Plan:raeumlicherGeltungsbereich oder eine Erfassung vor der Konvertierung
- EPSG:Codes werden derzeit in den Regeln festgehalten. Hier ist es evtl. sinnvoll diese für gml:envelope zu übernehmen
- Ein XPlan-Dokument sollte (im Normalfall) zuerst einen Plan, dann einen Bereich und dann jeweilige weitere FeatureMember enthalten. Diese sind über xlink-Relationen zu deren gml-ids miteinander assoziiert. Zum Beispiel sieht die GML-Zeile für eine Verknüpfung von einer Relation von einem Bereich zu einem spezifischen Planzeichen-Objekt wie folgt aus:
  `<xplan:inhaltRPlan xlink:id="#GML_345345345534534-23423423-3453453-23423"/>`
  Das # wird für XLink verwendet. Die GML-ID ist danach die GML ID des spezifischen Planzeichen-Objekts. Umgekehrt sollte jedes Objekt eine Referenz auf einen Bereich erhalten die wie folgt aussehen kann
  `<xplan:gehoertZuRP_Bereich xlink:id="#GML_8978678678673423423"/>`
- Jedes Beispieldokument in XPlan hat im Normalfall die Namespaces xplan: vor jedem XPlan-Element (bis auf das Root-Element XPlanAuszug). Dies sollte falls möglich übernommen werden. Beispiel: Statt:
  `<ebene>0</ebene>`
  `<xplan:ebene>0</xplan:ebene>`
- XML ist case-sensitive, bzw. wird so verwendet (http://stackoverflow.com/questions/7414747/is-xml-case-sensitive). Groß- und Kleinschreibung von Elementen muss zur korrekten Validierung noch für ALLE Elemente und Attribute berücksichtigt werden. Beispiel:
  Nicht `<rp_naturschutzrechtlichesschutzgebiet id="ba65eb9a-c98f-11e5-bbdd-eb2232bd1de7"></rp_naturschutzrechtlichesschutzgebiet>` sondern
  `<xplan:RP_NaturschutzrechtlichesSchutzgebiet gml:id="ba65eb9a-c98f-11e5-bbdd-eb2232bd1de7"></xplan:RP_NaturschutzrechtlichesSchutzgebiet>`
- Leere Elemente sollten nicht ausgegeben werden. Zum Beispiel kann `<hatgenerattribut/>` weggelassen werden. Dies ist in den Beispieldateien für XPlan und INSPIRE der Fall, verringert die Größe der Datei und macht sie übersichtlicher.
- Für gml-ids muss der Namespace gml: übernommen werden. D.h. statt `<rp_naturschutzrechtlichesschutzgebiet id="ba65eb9a-c98f-11e5-bbdd-eb2232bd1de7">` sollte `<xplan:RP_NaturschutzrechtlichesSchutzgebiet gml:id="ba65eb9a-c98f-11e5-bbdd-eb2232bd1de7">` verwendet werden
- (Low-Priority). In den XPlan-Dateien (und meines Wissens auch in einigen INSPIRE-Dateien) haben gml-IDs oft ein GML_ vor der eigentlichen ID. Dies könnte bei der Generierung der IDs miteingefügt werden und kann die Bearbeitung, z.B. für eine XSLT erleichtern
- (Low-Priority) Geometrieelemente in GML haben gleichfalls ein Attribut gml:id, damit diese per Xlink verwiesen werden können. Dieser Fall kommt normalerweise in XPlan selbst nicht vor, es sollte aber miteingefügt werden.

**Comment by RKraetschmer** [comment]
Nach Upload der neuesten XSDs auf der Homepage sollte aus XPlanAuszug devk entnommen werden. XPlanAuszug sollte nun wie folgt aussehen:
`<XPlanAuszug xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:wfs="http://www.opengis.net/wfs"
xmlns:gml="http://www.opengis.net/gml"
xmlns:gml="http://www.opengis.net/gml"
xmlns:xlink="http://www.w3.org/1999/xlink"
xmlns:xplan="http://xplan-raumordnung.de/model/xplangml/raumordnungsmodell"
xmlns="http://xplan-raumordnung.de/model/xplangml/raumordnungsmodell"
xsi:schemaLocation="http://xplan-raumordnung.de/model/xplangml/raumordnungsmodell/ ../../Schema/XPlanung-Operationen.xsd">
`

**Comment by RKraetschmer** [comment]
GML hat eine andere Umlaufrichtung als Shape-Dateien. Deswegen muss diese per PostGIS Funktion geändert werden.

**Comment by pkorduan** [comment]
Ist erledigt.
