### ISSUE TITLE
BBSR-13 Fix SQL-Editor

### ISSUE THREAD

**Issue by pkorduan** [srahn/kvwmap#27]
- [x] Bei vorselektiertem Featuretyp Featuretyp-Attributetabelle schon laden.
- [x] Bei Aufruf des SQL-Editors aus dem Formular einer neuen Bereichsregel konvertierung_id über bereich_gml_id abfragen.
- [x] Attributzuweisung für CASES korrigieren
  Wenn man über wenn dann mehrere Cases zum SQL hinzufügen möchte, müssen die WHEN THEN Klauseln innerhalb der CASE END hinzugefügt werden und nicht wie jetzt als neues Attribut mit einer vollständigen CASE WHEN THEN END Klausel.
- [x] Pflichtattribute prüfen
  Bevor ein SQL-Statement mit dem Pfeil zur Regel zugeordnet wird, muss geprüft werden ob alle Pflichtattribute des ausgewählten FeatureTypen in dem SQL-Statement vorkommen. Wenn nicht entsprechender Hinweis. Vielleicht auch die Pflichtelemente in der Tabelle des FeatureTypen gleich hervorheben in einer anderen Farbe oder Fett geschrieben.
- [x] Den SQL-Editor so bauen, dass beim Aufruf das in der Regel vorhandene SQL übernommen wird, so das es mit den Möglichkeiten des SQL-Editors bearbeitet und ergänzt werden kann.
- [x] Die Schaltflächen in der Attributzuweisung vergrößern.
- [x] Umstellung aller Ajax Requests
  Alle Ajax Requests, die auf views des Regeleditors zugreifen, sollten über xplankonverter/control/index.php und entsprechende Cases mit go Variablen laufen, damit sie abgesichert werden können und die config.php und die DB connection von GUI nutzen.

**Comment by RKraetschmer** [comment]
- Attributzuweisungen für CASES Issue fixed
- Pflichtattribute Issue fixed. Sie sind fett und mit \* hervorgehoben. Weiterhin wird eine Warnung für rechtscharakter und bei Zentralen Orten für typ als Pflichtelemente angegeben, bis diese befüllt sind.
- Schaltflächengröße für Attributzuweisungen Issue fixed

**Comment by RKraetschmer** [comment]
Umstellung der Ajax Requests fixed
