### ISSUE TITLE
BBSR 17 - Fehler in der GML-Ausgabe von Geometrien bei nicht-abstrakten Ableitungen

### ISSUE THREAD

**Issue by RKraetschmer** [srahn/kvwmap#36]
- [x] Beim Erstellen einer XPlan-GML Datei kommt es zu einem Fehler in der GML-Erstellung, wenn 2 Klassen durch Regeln übernommen werden sollen, bei denen eine von der anderen abgeleitet ist und beide nicht abstrakt sind.

Ein Beispiel ist die Verwendung von RP_Freiraum und RP_NaturschutzrechtlichesSchutzgebiet im Beispielplan Havelland-Fläming des Landes Brandenburg.
Hier wird ein eigentlich für RP_NaturschutzrechtlichesSchutzgebiet bestimmtes Element sowohl für RP_Freiraum, als auch für das von RP_Freiraum abgeleitete Element RP_NaturschutzrechtlichesSchutzgebiet ausgelesen. Dies führt auch zu einer doppelten Verwendung der gml:id und der Geometrie, woran eine Validierung scheitert. Gleichfalls wird ein zusätzliches doppeltes Anführungszeichen (") in den Geometrieelementen erzeugt (da die gml:id mehrfach existiert). Die Datei ist somit nicht mehr well-formed. Der Fehler-Code sieht wie folgt aus:
```
<xplan:position>
      <gml:MultiSurface srsName="EPSG:25833" gml:id="GML_059c1968-bd64-11e6-a824-03ce8583237c_geom_0"">
        <gml:surfaceMember>
          <gml:Polygon gml:id="GML_059c1968-bd64-11e6-a824-03ce8583237c_geom_1"">
            <gml:exterior>
              <gml:LinearRing>
```

Die Fehlerquelle hängt voraussichtlich mit der Klasse model/build_gml.php ~Zeile 400 ff. zusammen, könnte aber ein generelleres Problem darstellen, wenn Nicht-Abstrakte Elemente von Nicht-Abstrakten Elementen ableiten. In XPlanung betrifft dies die Klassen RP_Freiraum, RP_Verkehr, RP_Siedlung und davon abgeleitete Klassen

**Comment by pkorduan** [comment]
Das wurde im Commit 8902289 gefixed.

Der Fehler mit den doppelten " kommt nicht von den doppelten Objekten wegen doppeltem Auslesen der Objekte von Supperklassen, sondern weil in gml_ids, die von ST_AsGml() erzeugt werden auch Texte rauskommen können, die hinten ein " haben und somit im XML ein "".

Das Problem mit den doppelten Objekten (Superklasse bei Subklasse noch mal ausgelesen) wurde behoben in dem zu jeder Klasse die Subklassen abgefragt werden (RP_Object->get_sub_classes) und wenn es welche gibt, wird die Klasse (ist ja dann eine Superklasse) mit seinen Subklassen gejoint und nur die Objekte der Superklasse ausgelesen, die keine Objekte in den Subklassen haben. siehe $table_sql und $where_sql in RP_Object->get_object_rows()
