### ISSUE TITLE
BBSR-19 Aktualisierung des aktuellsten Modells

### ISSUE THREAD

**Issue by pkorduan** [srahn/kvwmap#41]
- [x] Implementierung XPlan-5.0
- [x] Anpassung der Migration der Datenbank in /plugins/xplankonverter/db/postgresql/schema.
Um den Konverter zu migrieren, müssen die Schemata für xplankonverter, xplan_gml und xplan_uml gleichfalls in der korrekten Fassung übertragen werden.
- [x] Test der XPlanGML - Ausgabe

**Comment by RKraetschmer** [comment]
Ist abgeschlossen. Weitere Änderungen werden in anderen Issues bearbeitet.
