### ISSUE TITLE
BBSR-23 Anpassung der Migration des Konverters

### ISSUE THREAD

**Issue by RKraetschmer** [srahn/kvwmap#45]
Anpassung der Migration der Datenbank in /plugins/xplankonverter/db/postgresql/schema.
 Um den Konverter zu migrieren, müssen die Schemata für xplankonverter, xplan_gml und xplan_uml gleichfalls in der korrekten Fassung übertragen werden.

**Comment by pkorduan** [comment]
Wir in BBSR-19 Abgearbeitet
