### ISSUE TITLE
BBSR-24 Fehler bei der Durchführung der Konvertierung

### ISSUE THREAD

**Issue by RKraetschmer** [srahn/kvwmap#51]
Bei der Durchführung von Konvertierungen werden folgende Warnungen ausgegeben:

> Warning: pg_query(): Query failed: ERROR: relation "xplan_shapes_14.shp_table" does not exist LINE 3: xplan_shapes_14.shp_table AS shape ^ in /var/www/apps/konverter/plugins/xplankonverter/model/regel.php on line 277

Durch diese werden Daten der Shapes nicht in das xplan_gml PostGIS-Schema geschrieben werden.
"shp_table" wurde bei einem früheren Schritt an alle FROM Statements angehängt, um die Eindeutigkeit einiger Attribute sicherzustellen. Der Fehler kam aber erst ab einem späteren Zeitpunkt auf.

**Comment by pkorduan** [comment]
Abgearbeitet in devlopment Commit 2223259
