### ISSUE TITLE
BBSR-26 Löschen von Layern von gelöschten Konvertierungen

### ISSUE THREAD

**Issue by RKraetschmer** [srahn/kvwmap#57]
Trotz Löschen von Konvertierungen werden Shapes und Konvertierung weiterhin in der Karte angezeigt. Es gibt für den Nutzer keinen direkten Weg diese zu löschen.

Beim Löschen von Konvertierungen sollten dazugehörige Layer und Daten automatisch mitgelöscht werden.

Eine Anfrage hierzu kam aus Sachsen Anhalt. Im Bundesland wurden bereits mehrere Testkonvertierungen durchgeführt und wieder gelöscht, während diese in der Karte verbleiben.

**Comment by pkorduan** [comment]
Sollte im neuen XPlanung Portal mit XPlanung Vesion 5.1 erledigt sein. Prüfen
