### ISSUE TITLE
BBSR-27 Regeleditor kann XPlan-Klassen nicht anzeigen

### ISSUE THREAD

**Issue by RKraetschmer** [srahn/kvwmap#58]
Beim Regeleditor tritt ein Fehler beim Laden von XPlan-Klassen aus der Datenbank auf, wenn diese im Regelformular oder innerhalb der Regeleditors angegeben werden.
Die Fehlermeldung lautet:
"Warnung: pg_fetch_row() expects parameter 1 to be resource, null given in /var/www/apps/konverter/plugins/xplankonverter/view/regeleditor/getxplanattributes.php on line 13."

Der hierzu relevante CASE lässt sich in PostgreSQL oder als gesonderte Ajax ausführen und sendet laut Netzwerkbericht von Chrome DevTools oder Firebug auch die korrekten Parameter und die korrekte Abfrage an die Datenbank.
Ajax-Requests mit ähnlicher CASE-Strultur (z.B. xplankonverter_regeleditor_getshapeattributes oder ..._getshapeattributes2) funktionieren weiterhin.

**Comment by pkorduan** [comment]
Behoben
