### ISSUE TITLE
BBSR-28 Fehler im Geometrieeditor Planformular

### ISSUE THREAD

**Issue by RKraetschmer** [srahn/kvwmap#60]
Im Geometrieeditor kann derzeit kein räumlicher Geltungsbereich aus Geometrien übernommen werden und deswegen auch kein Plan angelegt werden.
Hinweis heirzu kam von Herrn Holger Naumann aus Anhalt-Bitterfeld-Wittenberg, der auch ein Video des Fehlers hochgeladen hat: https://c.gmx.net/@339361156248376600/s0SbyFKIS5G9joY6OUth1Q
(Das Anlegen eines Plans funktioniert weiterhin über die Datenbank)

**Comment by pkorduan** [comment]
Fehler lag nicht an kvwmap sondern in der login Funktion der Site xplan-raumordnung.de wo für kvwmap geforderte Session-Parameter nicht gesetzt wurden.
