### ISSUE TITLE
BBSR-32 Geltungsbereiche von Shapes übernehmen

### ISSUE THREAD

**Issue by pkorduan** [srahn/kvwmap#68]
Derzeit lassen sich die Geltungsbereiche nur in der Karte einzeichnen oder von vorhandenen Polygonen über den Geometrieeditor übernehmen. Diese Vorgehensweise ist für Nutzer nicht einfach genug.
Besser wäre es wenn der Nutzer einfach eine Shape-Datei auswählen kann und die erste Geometrie darin wird als räumlicher Geltungsbereich übernommen und zwar dann auch in dem EPSG der Konvertierung und nicht in der die in der Layerdefinition von Pläne und Bereiche angegeben ist. Des Weiteren kann dann die on-the-fly Transformation der Geometrien bei allen Validierungen wegfallen, weil dann alles per se in einem System ist. Die Editierung der Geometrie sollte dann standardmäßig zugeklappt sein.
- [x] View für Auswahl von Shape-Datei mit dem Umring
- [ ] Cases im Controller zum Aufruf der Auswahl und dem Setzen der Umringe von Plan und Bereich
- [x] Funktion zum Setzen des Umrings im Plan- und Bereichsobjekt

**Comment by RKraetschmer** [comment]
Die Werkzeugleiste des Geometrieeditors reagiert derzeit nicht mehr (ggf. im Zusammenhang mit der Umstellung der Darstellung).

**Comment by pkorduan** [comment]
Das Feature ist bereits umgesetzt.
