### ISSUE TITLE
BBSR-6 Stylen der gml class layer

### ISSUE THREAD

**Issue by RKraetschmer** [srahn/kvwmap#9]
Anpassen der Funktion add_style in kvwmap.php damit man variable Styles erzeugen kann. Konfigurieren der Stylesettings in xplankonverter controller an Hand einer Umsetzungstabelle sld Styles to featuretype.

**Comment by pkorduan** [comment]
Wird nicht weiter verfolgt, da die Layer, die für gml verwendet werden alle als Templates vordefiniert und in kvwmap gestyled werden. Beim Anlegen von neuen Layern in Plänen werden die jeweiligen Template-Layer kopiert.
